import Mathlib.Topology.Sets.Compacts
import Mathlib.Topology.Defs.Induced
import Mathlib.Topology.RestrictGen

open Set Set.Notation Topology

/-!
# Kspaces and the k-ification

In this file we will define k-spaces and the k-ification and prove basic properties about them.

## Main definitions
* `KSpace`: A k-space is a topological space in which a set `A` is open iff for every compact set
  `B`, the intersection `A ∩ B` is open in `B`.
* `instkification`: For a topological space `X` one can define another topology on `X` as follows:
  `A` is open iff for all compact sets `B`, the intersection `A ∩ B` is open in `B`.

## Main results
* `kspace_of_WeaklyLocallyCompactSpace`: every weakly locally compact space is a k-space
* `kspace_of_SequentialSpace`: every sequential space is a k-space
* `isCompact_iff_isCompact_in_kification`: The compact sets of a topological space and its
  k-ification agree.
* `kspace_kification`: The k-ification makes any space into a k-space.
* `kification_kspace_eq_self`: The k-ification of a k-space `X` preserves the topology on `X`.
* `continuous_kification_of_continuousOn_compact`: A map going to the k-ification of a topological
  space `X` is continuous if map going to `X` is continuous when restricted to every compact set.

## References
* [J. Munkres, *Topology*]
* <https://en.wikipedia.org/wiki/Compactly_generated_space>
-/

noncomputable section

/-! ### K-spaces-/

/-- A space is a KSpace if the topology is generated by the compact sets.-/
class KSpace  (X : Type*) [TopologicalSpace X] : Prop where
  /-- A space is a k-space if the topology is generated by the compact sets.-/
  restrictGenTopology : RestrictGenTopology (X := X) {K | IsCompact K}

namespace KSpace

variable {X : Type*} [TopologicalSpace X] [KSpace X]

/-- A set `A` in a k-space is open iff for every compact set `K`, the intersection `K ∩ A` is
  open in `K`.-/
lemma isOpen_iff (A : Set X) : IsOpen A ↔ ∀ K, IsCompact K → IsOpen (K ↓∩ A) :=
  RestrictGenTopology.isOpen_iff restrictGenTopology

/-- A set `A` in a k-space is closed iff for every compact set `K`, the intersection `K ∩ A` is
  closed in `K`.-/
lemma isClosed_iff (A : Set X) : IsClosed A ↔ ∀ K, IsCompact K → IsClosed (K ↓∩ A) :=
  RestrictGenTopology.isClosed_iff restrictGenTopology

/-- If every set `A` is open if for every compact `K` the intersection `K ∩ A` is open in `K`,
  then the space is a k-space. -/
lemma kspace_of_isOpen {X : Type*} [TopologicalSpace X]
    (h : ∀ (A : Set X), (∀ K, IsCompact K → IsOpen (K ↓∩ A)) → IsOpen A) : KSpace X where
  restrictGenTopology := {isOpen_of_forall_induced := h}

/-- If every set `A` is closed if for every compact `K` the intersection `K ∩ A` is closed in `K`,
  then the space is a k-space. -/
lemma kspace_of_isClosed {X : Type*} [TopologicalSpace X]
    (h : ∀ (A : Set X), (∀ K, IsCompact K → IsClosed (K ↓∩ A)) → IsClosed A) : KSpace X where
  restrictGenTopology := RestrictGenTopology.of_isClosed h

/-- Every weakly locally compact space is a k-space.-/
instance kspace_of_WeaklyLocallyCompactSpace {X : Type*} [TopologicalSpace X]
    [WeaklyLocallyCompactSpace X] : KSpace X where
  restrictGenTopology := RestrictGenTopology.isCompact_of_weaklyLocallyCompact

/-- Every sequential space is a k-space.-/
instance kspace_of_SequentialSpace {X : Type*} [TopologicalSpace X]
    [SequentialSpace X]: KSpace X where
  restrictGenTopology := RestrictGenTopology.isCompact_of_seq

/-- A type synonym used for the k-ification of a topological space.-/
def kification (X : Type*) := X

/--For a topological space `X` the k-ification is defined as:
  `A` is open iff for all compact sets `B`, the intersection `A ∩ B` is open in `B`.-/
instance instkification {X : Type*} [TopologicalSpace X] : TopologicalSpace (kification X) where
  IsOpen A := ∀ (K : Set X), IsCompact K → IsOpen (K ↓∩ A)
  isOpen_univ := by simp
  isOpen_inter A B hA hB K hK := by
    specialize hA K hK
    specialize hB K hK
    exact hA.inter hB
  isOpen_sUnion s hs K hK := by
    rw [preimage_val_sUnion]
    apply isOpen_sUnion
    rintro _ ⟨u, hu, rfl⟩
    exact hs u hu K hK

/-- A set `A` is the k-ification is open iff for all compact sets `K`,
  the intersection `K ∩ A` is open in `K`.-/
lemma kification.isOpen_iff {X : Type*} [TopologicalSpace X] {A : Set (kification X)} :
    IsOpen (X := kification X) A ↔
    ∀ (K : Set X), IsCompact K → IsOpen (K ↓∩ A) := by
  rfl

/-- A set `A` is the k-ification is closed iff for all compact sets `K`,
  the intersection `K ∩ A` is closed in `K`.-/
lemma kification.isClosed_iff {X : Type*} [TopologicalSpace X] {A : Set (kification X)} :
    IsClosed (X := kification X) A ↔
    ∀ (K : Set X), IsCompact K → IsClosed (K ↓∩ A):= by
  rw [← isOpen_compl_iff, isOpen_iff]
  congrm ∀ (K : Set X), IsCompact K → ?_
  exact isOpen_compl_iff

/-- The map taking a space to its k-ification.-/
def tokification (X : Type*) : X ≃ kification X :=
  ⟨fun x ↦ x, fun x ↦ x, fun _ ↦ rfl, fun _ ↦ rfl⟩

lemma tokification_image {X : Type*} [TopologicalSpace X] (A : Set X) :
    tokification X '' A = A := by
  simp [tokification]

lemma tokification_symm_image {X : Type*} [TopologicalSpace X] (A : Set X) :
    (tokification X).symm '' A = A := by
  simp [tokification]

lemma continuous_fromkification {X : Type*} [t : TopologicalSpace X] :
    Continuous (tokification X).symm where
  isOpen_preimage A hA := by
    rw [kification.isOpen_iff]
    intros
    exact isOpen_induced hA

lemma isOpenMap_tokification {X : Type*} [t: TopologicalSpace X] : IsOpenMap (tokification X) := by
  intro A hA
  rw [kification.isOpen_iff]
  intro K hK
  simp [tokification, isOpen_induced hA]

/-- The k-ification is finer than the original topology.-/
lemma kification_le {X : Type*} [t : TopologicalSpace X] :
    (instkification : TopologicalSpace X) ≤ (t : TopologicalSpace X) := by
  rw [← continuous_id_iff_le]
  change Continuous (tokification X).symm
  exact continuous_fromkification

lemma isCompact_iff_isCompact_tokification_image {X : Type*} [TopologicalSpace X] (K : Set X) :
    IsCompact K ↔ IsCompact (tokification X '' K) := by
  constructor
  · intro hK
    rw [isCompact_iff_finite_subcover]
    intro ι U hU hKU
    simp_rw [kification.isOpen_iff] at hU
    choose U' hU' using hU
    have hKU' : K ⊆ ⋃ i, U' i K hK := by
      simp_rw [← inter_eq_left, inter_iUnion,
        Subtype.preimage_coe_eq_preimage_coe_iff.mp (hU' _ K hK).2, ← inter_iUnion, inter_eq_left]
      rw [tokification_image] at hKU
      exact hKU
    rcases (isCompact_iff_finite_subcover.1 hK) (fun i ↦ U' i K hK)
      (fun i ↦ (hU' i K hK).1) hKU' with ⟨ι', hι'⟩
    use ι'
    simp_rw [tokification_image, ← inter_eq_left, inter_iUnion,
      ← Subtype.preimage_coe_eq_preimage_coe_iff.mp (hU' _ K hK).2, ← inter_iUnion, inter_eq_left]
    exact hι'
  · intro hK
    simp only [tokification_image] at hK
    suffices IsCompact ((tokification X).symm '' K) by
      simpa [tokification_symm_image]
    exact hK.image continuous_fromkification
